project_id = "mggqklxjeraorishluty"

[functions.upload-prefill-data]
verify_jwt = false

[functions.get-prefill-data]
verify_jwt = false

[functions.ai-validate-responses]
verify_jwt = false

[functions.ai-autocode-responses]
verify_jwt = false

[functions.ai-trust-score]
verify_jwt = false
