// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mggqklxjeraorishluty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZ3FrbHhqZXJhb3Jpc2hsdXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzkyNzksImV4cCI6MjA3MDg1NTI3OX0.QTFQB3RcVsX7e375zMJBmLsZ0Aj72lkqsRz5jCSaA0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});